#####################################################################
#####################################################################
###           _____      _      _____       _            __       ###
###          |  ___|    (_)    /  ___|     | |          / _|      ###
###          | |__ _ __  _  ___\ `--. _ __ | | ___  ___| |_       ###
###          |  __| '_ \| |/ __|`--. \ '_ \| |/ _ \/ _ \  _|      ###
###          | |__| |_) | | (__/\__/ / |_) | |  __/  __/ |        ###
###          \____/ .__/|_|\___\____/| .__/|_|\___|\___|_|        ###
###               | |                | |                          ###
###               |_|                |_|                          ###
###                                                               ###
###      _           ___ _       ___          _   _               ###
###     | |__ _  _  | _ ) |_ ___| _ ) __ _ __| |_(_)__ _ _ _      ###
###     | '_ \ || | | _ \  _/ _ \ _ \/ _` (_-<  _| / _` | ' \     ###
###     |_.__/\_, | |___/\__\___/___/\__,_/__/\__|_\__,_|_||_|    ###
###           |__/                                                ###
#####################################################################
#####################################################################
mainSettings:
  languagefile: lang.yml
auto-update:
  check: true
  update: true
# If unsafeUpdates are enabled it will also download plugins versions for higher game versions. If not it will just download the plugin if the game-version fits even if there's a newer version of the plugin.
  unsafeUpdates: false
scoreboard:
  - '&a&lWins'
  - '%wins%'
  - '&1'
  - '&c&lLosses'
  - '%losses%'
  - '&2'
  - '&6&lPoints'
  - '%points%'
  - '&3'
  - '&a&lTotal Wins'
  - '%totalWins%'
  - '&4'
  - '&c&lTotal Losses'
  - '%totalLosses%'
joinsigns:
  waitingForPlayers:
    lines:
      1: '&l&9%arena%'
      2: '&2JOINABLE'
      3: '%players% / %maxPlayers%'
      4: '&aClick to join'
  full:
    lines:
      1: '&l&9%arena%'
      2: '&4FULL'
      3: '%players% / %maxPlayers%'
      4: 'Countdown: &c%countdown%'
  inProgress:
    lines:
      1: '&l&9%arena%'
      2: '&4IN GAME'
      3: '%players% / %maxPlayers%'
      4: '&aClick to spectate'
  disabled:
    lines:
      1: '&l&9%arena%'
      2: '&cDISABLED'
      3: ''
      4: ''
stats:
  enable: true
expertsOnly:
  stats:
    threadPoolSettings:
      corePoolSize: 1
      maximumPoolSize: 1
      keepAliveTimeInMilliSeconds: 0