#####################################################################
#####################################################################
###   ______                        _____       _            __   ###
###  |  ____|                      / ____|     | |          / _|  ###
###  | |__ __ _ _ __   ___ _   _  | (___  _ __ | | ___  ___| |_   ###
###  |  __/ _` | '_ \ / __| | | |  \___ \| '_ \| |/ _ \/ _ \  _|  ###
###  | | | (_| | | | | (__| |_| |  ____) | |_) | |  __/  __/ |    ###
###  |_|  \__,_|_| |_|\___|\__, | |_____/| .__/|_|\___|\___|_|    ###
###                         __/ |        | |                      ###
###                        |___/         |_|                      ###
###      _           ___ _       ___          _   _               ###
###     | |__ _  _  | _ ) |_ ___| _ ) __ _ __| |_(_)__ _ _ _      ###
###     | '_ \ || | | _ \  _/ _ \ _ \/ _` (_-<  _| / _` | ' \     ###
###     |_.__/\_, | |___/\__\___/___/\__,_/__/\__|_\__,_|_||_|    ###
###           |__/                                                ###
#####################################################################
#####################################################################
mainSettings:
  languagefile: lang_en.yml
scoreboard:
  - '&a&lWins'
  - '%wins%'
  - '&1'
  - '&c&lLosses'
  - '%losses%'
  - '&2'
  - '&6&lPoints'
  - '%points%'
  - '&3'
  - '&a&lTotal Wins'
  - '%totalWins%'
  - '&4'
  - '&c&lTotal Losses'
  - '%totalLosses%'
stats:
  enable: true
expertsOnly:
  stats:
    threadPoolSettings:
      corePoolSize: 1
      maximumPoolSize: 1
      keepAliveTimeInMilliSeconds: 0